version: "3.9"

services:
  web:
    build: .
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6001:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--dir", "/data"]
